### ISSUE TITLE
T shirts 

### ISSUE THREAD

**Issue by knr15** [USM-IEEE/secon-2018#7]
create an svg design. Due date April 6, 2018 reviewed @mlaga97

**Comment by mlaga97** [comment]
T-shirt sizes have been added to the member spreadsheet posted in discord.

**Comment by mikparil** [comment]
I've payed a dude 5 Dollars on a website to design a mechanical Eagle vector image for our logo in the case that the person who is making our logo does not pull through. Once I get the logo and the list of people who needs shirts(and their shirt size) i'm designing the shirt and sending the order out Monday or Tuesday next week. The shirts should then get here by either Friday or the following Monday.

**Comment by mikparil** [comment]
Here's the design, this can be used for the flag and the other thing we needed aswell
![ieee eagle shirt_1](https://user-images.githubusercontent.com/38087703/38449439-ad92e28a-39d4-11e8-8068-43e7cef73217.png)
![ieee eagle](https://user-images.githubusercontent.com/38087703/38449440-ada9c9a0-39d4-11e8-8d8a-7d79448334a5.png)

**Comment by mlaga97** [comment]
The t-shirts have been ordered and will come in on April 17.
